2016-09-09 15:18:41:551  INFO BATTLE:main - effect模块初始化开始。
2016-09-09 15:18:41:577  INFO BATTLE:main - effect模块初始化完成。
2016-09-09 15:18:41:578  INFO BATTLE:main - battle模块初始化开始
2016-09-09 15:18:41:583  INFO BATTLE:main - battle阵型信息初始化完成
2016-09-09 15:18:41:589  INFO BATTLE:main - battle AI信息初始化完成
2016-09-09 15:18:41:605  INFO BATTLE:main - 战场信息初始化完成
2016-09-09 15:18:41:605  INFO BATTLE:main - battle模块初始化完成
2016-09-09 15:18:41:746  INFO BATTLE:main - BUFF模块初始化开始
2016-09-09 15:18:41:761  INFO BATTLE:main - BUFF模块初始化完成
2016-09-09 15:19:19:289  INFO BATTLE:main - effect模块初始化开始。
2016-09-09 15:19:19:321  INFO BATTLE:main - effect模块初始化完成。
2016-09-09 15:19:19:321  INFO BATTLE:main - battle模块初始化开始
2016-09-09 15:19:19:321  INFO BATTLE:main - battle阵型信息初始化完成
2016-09-09 15:19:19:461  INFO BATTLE:main - battle AI信息初始化完成
2016-09-09 15:19:19:461  INFO BATTLE:main - 战场信息初始化完成
2016-09-09 15:19:19:461  INFO BATTLE:main - battle模块初始化完成
2016-09-09 15:19:19:649  INFO BATTLE:main - BUFF模块初始化开始
2016-09-09 15:19:19:664  INFO BATTLE:main - BUFF模块初始化完成
2016-09-09 15:19:40:910 ERROR BATTLE:mkdb.Worker.procedure.38 - 在角色4097下线的情况下，使用了该角色的ERole。因为ERole是内存表，数据可能没有  ，请根据堆栈内容确认此使用是否正确。
2016-09-09 15:19:40:910 ERROR BATTLE:mkdb.Worker.procedure.38 - 	at java.lang.Thread.getStackTrace(Unknown Source)
	at fire.pb.effect.RoleImpl.<init>(RoleImpl.java:80)
	at fire.pb.skill.SceneSkillRole.equip(SceneSkillRole.java:165)
	at fire.pb.role.PCreateRole.process(PCreateRole.java:503)
	at mkdb.Procedure.call(Procedure.java:109)
	at mkdb.Transaction.perform(Transaction.java:279)
	at mkdb.ProcedureFuture.run(ProcedureFuture.java:80)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
	at mkdb.Worker.run(Worker.java:32)

2016-09-09 15:19:40:926 ERROR BATTLE:mkdb.Worker.procedure.38 - 在角色4097下线的情况下，使用了该角色的ERole。因为ERole是内存表，数据可能没有  ，请根据堆栈内容确认此使用是否正确。
2016-09-09 15:19:40:926 ERROR BATTLE:mkdb.Worker.procedure.38 - 	at java.lang.Thread.getStackTrace(Unknown Source)
	at fire.pb.effect.RoleImpl.<init>(RoleImpl.java:80)
	at fire.pb.buff.BuffRoleImpl.getERole(BuffRoleImpl.java:252)
	at fire.pb.buff.continual.ConstantlyBuff.impact(ConstantlyBuff.java:102)
	at fire.pb.buff.BuffAgent.addCBuff(BuffAgent.java:294)
	at fire.pb.skill.SceneSkillRole.equip(SceneSkillRole.java:220)
	at fire.pb.role.PCreateRole.process(PCreateRole.java:503)
	at mkdb.Procedure.call(Procedure.java:109)
	at mkdb.Transaction.perform(Transaction.java:279)
	at mkdb.ProcedureFuture.run(ProcedureFuture.java:80)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
	at mkdb.Worker.run(Worker.java:32)

2016-09-09 15:19:40:926 ERROR BATTLE:mkdb.Worker.procedure.38 - 在角色4097下线的情况下，使用了该角色的ERole。因为ERole是内存表，数据可能没有  ，请根据堆栈内容确认此使用是否正确。
2016-09-09 15:19:40:926 ERROR BATTLE:mkdb.Worker.procedure.38 - 	at java.lang.Thread.getStackTrace(Unknown Source)
	at fire.pb.effect.RoleImpl.<init>(RoleImpl.java:80)
	at fire.pb.skill.SceneSkillRole.equip(SceneSkillRole.java:165)
	at fire.pb.role.PCreateRole.process(PCreateRole.java:503)
	at mkdb.Procedure.call(Procedure.java:109)
	at mkdb.Transaction.perform(Transaction.java:279)
	at mkdb.ProcedureFuture.run(ProcedureFuture.java:80)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
	at mkdb.Worker.run(Worker.java:32)

2016-09-09 15:19:40:926 ERROR BATTLE:mkdb.Worker.procedure.38 - 在角色4097下线的情况下，使用了该角色的ERole。因为ERole是内存表，数据可能没有  ，请根据堆栈内容确认此使用是否正确。
2016-09-09 15:19:40:926 ERROR BATTLE:mkdb.Worker.procedure.38 - 	at java.lang.Thread.getStackTrace(Unknown Source)
	at fire.pb.effect.RoleImpl.<init>(RoleImpl.java:80)
	at fire.pb.buff.BuffRoleImpl.getERole(BuffRoleImpl.java:252)
	at fire.pb.buff.continual.ConstantlyBuff.impact(ConstantlyBuff.java:102)
	at fire.pb.buff.BuffAgent.addCBuff(BuffAgent.java:294)
	at fire.pb.skill.SceneSkillRole.equip(SceneSkillRole.java:220)
	at fire.pb.role.PCreateRole.process(PCreateRole.java:503)
	at mkdb.Procedure.call(Procedure.java:109)
	at mkdb.Transaction.perform(Transaction.java:279)
	at mkdb.ProcedureFuture.run(ProcedureFuture.java:80)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
	at mkdb.Worker.run(Worker.java:32)

2016-09-09 15:19:40:926 ERROR BATTLE:mkdb.Worker.procedure.38 - 在角色4097下线的情况下，使用了该角色的ERole。因为ERole是内存表，数据可能没有  ，请根据堆栈内容确认此使用是否正确。
2016-09-09 15:19:40:926 ERROR BATTLE:mkdb.Worker.procedure.38 - 	at java.lang.Thread.getStackTrace(Unknown Source)
	at fire.pb.effect.RoleImpl.<init>(RoleImpl.java:80)
	at fire.pb.skill.SceneSkillRole.equip(SceneSkillRole.java:165)
	at fire.pb.role.PCreateRole.process(PCreateRole.java:503)
	at mkdb.Procedure.call(Procedure.java:109)
	at mkdb.Transaction.perform(Transaction.java:279)
	at mkdb.ProcedureFuture.run(ProcedureFuture.java:80)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
	at mkdb.Worker.run(Worker.java:32)

2016-09-09 15:19:40:926 ERROR BATTLE:mkdb.Worker.procedure.38 - 在角色4097下线的情况下，使用了该角色的ERole。因为ERole是内存表，数据可能没有  ，请根据堆栈内容确认此使用是否正确。
2016-09-09 15:19:40:926 ERROR BATTLE:mkdb.Worker.procedure.38 - 	at java.lang.Thread.getStackTrace(Unknown Source)
	at fire.pb.effect.RoleImpl.<init>(RoleImpl.java:80)
	at fire.pb.buff.BuffRoleImpl.getERole(BuffRoleImpl.java:252)
	at fire.pb.buff.continual.ConstantlyBuff.impact(ConstantlyBuff.java:102)
	at fire.pb.buff.BuffAgent.addCBuff(BuffAgent.java:294)
	at fire.pb.skill.SceneSkillRole.equip(SceneSkillRole.java:220)
	at fire.pb.role.PCreateRole.process(PCreateRole.java:503)
	at mkdb.Procedure.call(Procedure.java:109)
	at mkdb.Transaction.perform(Transaction.java:279)
	at mkdb.ProcedureFuture.run(ProcedureFuture.java:80)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
	at mkdb.Worker.run(Worker.java:32)

2016-09-09 15:19:40:926 ERROR BATTLE:mkdb.Worker.procedure.38 - 在角色4097下线的情况下，使用了该角色的ERole。因为ERole是内存表，数据可能没有  ，请根据堆栈内容确认此使用是否正确。
2016-09-09 15:19:40:926 ERROR BATTLE:mkdb.Worker.procedure.38 - 	at java.lang.Thread.getStackTrace(Unknown Source)
	at fire.pb.effect.RoleImpl.<init>(RoleImpl.java:80)
	at fire.pb.skill.SceneSkillRole.equip(SceneSkillRole.java:165)
	at fire.pb.role.PCreateRole.process(PCreateRole.java:503)
	at mkdb.Procedure.call(Procedure.java:109)
	at mkdb.Transaction.perform(Transaction.java:279)
	at mkdb.ProcedureFuture.run(ProcedureFuture.java:80)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
	at mkdb.Worker.run(Worker.java:32)

2016-09-09 15:19:40:926 ERROR BATTLE:mkdb.Worker.procedure.38 - 在角色4097下线的情况下，使用了该角色的ERole。因为ERole是内存表，数据可能没有  ，请根据堆栈内容确认此使用是否正确。
2016-09-09 15:19:40:926 ERROR BATTLE:mkdb.Worker.procedure.38 - 	at java.lang.Thread.getStackTrace(Unknown Source)
	at fire.pb.effect.RoleImpl.<init>(RoleImpl.java:80)
	at fire.pb.buff.BuffRoleImpl.getERole(BuffRoleImpl.java:252)
	at fire.pb.buff.continual.ConstantlyBuff.impact(ConstantlyBuff.java:102)
	at fire.pb.buff.BuffAgent.addCBuff(BuffAgent.java:294)
	at fire.pb.skill.SceneSkillRole.equip(SceneSkillRole.java:220)
	at fire.pb.role.PCreateRole.process(PCreateRole.java:503)
	at mkdb.Procedure.call(Procedure.java:109)
	at mkdb.Transaction.perform(Transaction.java:279)
	at mkdb.ProcedureFuture.run(ProcedureFuture.java:80)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
	at mkdb.Worker.run(Worker.java:32)

2016-09-09 15:19:40:926 ERROR BATTLE:mkdb.Worker.procedure.38 - 在角色4097下线的情况下，使用了该角色的ERole。因为ERole是内存表，数据可能没有  ，请根据堆栈内容确认此使用是否正确。
2016-09-09 15:19:40:926 ERROR BATTLE:mkdb.Worker.procedure.38 - 	at java.lang.Thread.getStackTrace(Unknown Source)
	at fire.pb.effect.RoleImpl.<init>(RoleImpl.java:80)
	at fire.pb.skill.SceneSkillRole.equip(SceneSkillRole.java:165)
	at fire.pb.role.PCreateRole.process(PCreateRole.java:503)
	at mkdb.Procedure.call(Procedure.java:109)
	at mkdb.Transaction.perform(Transaction.java:279)
	at mkdb.ProcedureFuture.run(ProcedureFuture.java:80)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
	at mkdb.Worker.run(Worker.java:32)

2016-09-09 15:19:40:926 ERROR BATTLE:mkdb.Worker.procedure.38 - 在角色4097下线的情况下，使用了该角色的ERole。因为ERole是内存表，数据可能没有  ，请根据堆栈内容确认此使用是否正确。
2016-09-09 15:19:40:926 ERROR BATTLE:mkdb.Worker.procedure.38 - 	at java.lang.Thread.getStackTrace(Unknown Source)
	at fire.pb.effect.RoleImpl.<init>(RoleImpl.java:80)
	at fire.pb.buff.BuffRoleImpl.getERole(BuffRoleImpl.java:252)
	at fire.pb.buff.continual.ConstantlyBuff.impact(ConstantlyBuff.java:102)
	at fire.pb.buff.BuffAgent.addCBuff(BuffAgent.java:294)
	at fire.pb.skill.SceneSkillRole.equip(SceneSkillRole.java:220)
	at fire.pb.role.PCreateRole.process(PCreateRole.java:503)
	at mkdb.Procedure.call(Procedure.java:109)
	at mkdb.Transaction.perform(Transaction.java:279)
	at mkdb.ProcedureFuture.run(ProcedureFuture.java:80)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
	at mkdb.Worker.run(Worker.java:32)

2016-09-09 15:19:40:941 ERROR BATTLE:mkdb.Worker.procedure.38 - 在角色4097下线的情况下，使用了该角色的ERole。因为ERole是内存表，数据可能没有  ，请根据堆栈内容确认此使用是否正确。
2016-09-09 15:19:40:941 ERROR BATTLE:mkdb.Worker.procedure.38 - 	at java.lang.Thread.getStackTrace(Unknown Source)
	at fire.pb.effect.RoleImpl.<init>(RoleImpl.java:80)
	at fire.pb.effect.RoleImpl.<init>(RoleImpl.java:71)
	at fire.pb.PInitRoleProp.process(PInitRoleProp.java:16)
	at mkdb.Procedure.call(Procedure.java:109)
	at fire.pb.role.PCreateRole.process(PCreateRole.java:509)
	at mkdb.Procedure.call(Procedure.java:109)
	at mkdb.Transaction.perform(Transaction.java:279)
	at mkdb.ProcedureFuture.run(ProcedureFuture.java:80)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
	at mkdb.Worker.run(Worker.java:32)

2016-09-09 15:19:41:066 ERROR BATTLE:mkdb.Worker.procedure.38 - 在角色4097下线的情况下，使用了该角色的ERole。因为ERole是内存表，数据可能没有  ，请根据堆栈内容确认此使用是否正确。
2016-09-09 15:19:41:066 ERROR BATTLE:mkdb.Worker.procedure.38 - 	at java.lang.Thread.getStackTrace(Unknown Source)
	at fire.pb.effect.RoleImpl.<init>(RoleImpl.java:80)
	at fire.pb.buff.BuffRoleImpl.getERole(BuffRoleImpl.java:252)
	at fire.pb.buff.continual.ConstantlyBuff.impact(ConstantlyBuff.java:102)
	at fire.pb.buff.BuffAgent.addCBuff(BuffAgent.java:294)
	at fire.pb.skill.SkillRole.addSkillBaseBuff(SkillRole.java:941)
	at fire.pb.skill.SkillRole.updateInbornWithSP(SkillRole.java:455)
	at fire.pb.role.PCreateRole.process(PCreateRole.java:533)
	at mkdb.Procedure.call(Procedure.java:109)
	at mkdb.Transaction.perform(Transaction.java:279)
	at mkdb.ProcedureFuture.run(ProcedureFuture.java:80)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
	at mkdb.Worker.run(Worker.java:32)

2016-09-09 15:19:41:066 ERROR BATTLE:mkdb.Worker.procedure.38 - 在角色4097下线的情况下，使用了该角色的ERole。因为ERole是内存表，数据可能没有  ，请根据堆栈内容确认此使用是否正确。
2016-09-09 15:19:41:066 ERROR BATTLE:mkdb.Worker.procedure.38 - 	at java.lang.Thread.getStackTrace(Unknown Source)
	at fire.pb.effect.RoleImpl.<init>(RoleImpl.java:80)
	at fire.pb.buff.BuffRoleImpl.getERole(BuffRoleImpl.java:252)
	at fire.pb.buff.continual.ConstantlyBuff.closure(ConstantlyBuff.java:153)
	at fire.pb.buff.BuffAgent.removeCBuff(BuffAgent.java:394)
	at fire.pb.buff.BuffAgent.processOverrideSelf(BuffAgent.java:305)
	at fire.pb.buff.BuffAgent.addCBuff(BuffAgent.java:283)
	at fire.pb.skill.SkillRole.addSkillBaseBuff(SkillRole.java:941)
	at fire.pb.skill.SkillRole.updateInbornWithSP(SkillRole.java:455)
	at fire.pb.role.PCreateRole.process(PCreateRole.java:533)
	at mkdb.Procedure.call(Procedure.java:109)
	at mkdb.Transaction.perform(Transaction.java:279)
	at mkdb.ProcedureFuture.run(ProcedureFuture.java:80)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
	at mkdb.Worker.run(Worker.java:32)

2016-09-09 15:19:41:066 ERROR BATTLE:mkdb.Worker.procedure.38 - 在角色4097下线的情况下，使用了该角色的ERole。因为ERole是内存表，数据可能没有  ，请根据堆栈内容确认此使用是否正确。
2016-09-09 15:19:41:066 ERROR BATTLE:mkdb.Worker.procedure.38 - 	at java.lang.Thread.getStackTrace(Unknown Source)
	at fire.pb.effect.RoleImpl.<init>(RoleImpl.java:80)
	at fire.pb.buff.BuffRoleImpl.getERole(BuffRoleImpl.java:252)
	at fire.pb.buff.continual.ConstantlyBuff.impact(ConstantlyBuff.java:102)
	at fire.pb.buff.BuffAgent.addCBuff(BuffAgent.java:294)
	at fire.pb.skill.SkillRole.addSkillBaseBuff(SkillRole.java:941)
	at fire.pb.skill.SkillRole.updateInbornWithSP(SkillRole.java:455)
	at fire.pb.role.PCreateRole.process(PCreateRole.java:533)
	at mkdb.Procedure.call(Procedure.java:109)
	at mkdb.Transaction.perform(Transaction.java:279)
	at mkdb.ProcedureFuture.run(ProcedureFuture.java:80)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
	at mkdb.Worker.run(Worker.java:32)

2016-09-09 15:19:41:066 ERROR BATTLE:mkdb.Worker.procedure.38 - 在角色4097下线的情况下，使用了该角色的ERole。因为ERole是内存表，数据可能没有  ，请根据堆栈内容确认此使用是否正确。
2016-09-09 15:19:41:066 ERROR BATTLE:mkdb.Worker.procedure.38 - 	at java.lang.Thread.getStackTrace(Unknown Source)
	at fire.pb.effect.RoleImpl.<init>(RoleImpl.java:80)
	at fire.pb.buff.BuffRoleImpl.getERole(BuffRoleImpl.java:252)
	at fire.pb.buff.continual.ConstantlyBuff.closure(ConstantlyBuff.java:153)
	at fire.pb.buff.BuffAgent.removeCBuff(BuffAgent.java:394)
	at fire.pb.buff.BuffAgent.processOverrideSelf(BuffAgent.java:305)
	at fire.pb.buff.BuffAgent.addCBuff(BuffAgent.java:283)
	at fire.pb.skill.SkillRole.addSkillBaseBuff(SkillRole.java:941)
	at fire.pb.skill.SkillRole.updateInbornWithSP(SkillRole.java:455)
	at fire.pb.role.PCreateRole.process(PCreateRole.java:533)
	at mkdb.Procedure.call(Procedure.java:109)
	at mkdb.Transaction.perform(Transaction.java:279)
	at mkdb.ProcedureFuture.run(ProcedureFuture.java:80)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
	at mkdb.Worker.run(Worker.java:32)

2016-09-09 15:19:41:066 ERROR BATTLE:mkdb.Worker.procedure.38 - 在角色4097下线的情况下，使用了该角色的ERole。因为ERole是内存表，数据可能没有  ，请根据堆栈内容确认此使用是否正确。
2016-09-09 15:19:41:066 ERROR BATTLE:mkdb.Worker.procedure.38 - 	at java.lang.Thread.getStackTrace(Unknown Source)
	at fire.pb.effect.RoleImpl.<init>(RoleImpl.java:80)
	at fire.pb.buff.BuffRoleImpl.getERole(BuffRoleImpl.java:252)
	at fire.pb.buff.continual.ConstantlyBuff.impact(ConstantlyBuff.java:102)
	at fire.pb.buff.BuffAgent.addCBuff(BuffAgent.java:294)
	at fire.pb.skill.SkillRole.addSkillBaseBuff(SkillRole.java:941)
	at fire.pb.skill.SkillRole.updateInbornWithSP(SkillRole.java:455)
	at fire.pb.role.PCreateRole.process(PCreateRole.java:533)
	at mkdb.Procedure.call(Procedure.java:109)
	at mkdb.Transaction.perform(Transaction.java:279)
	at mkdb.ProcedureFuture.run(ProcedureFuture.java:80)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
	at mkdb.Worker.run(Worker.java:32)

2016-09-09 15:19:41:129 ERROR BATTLE:mkdb.Worker.procedure.28 - 在角色4097下线的情况下，使用了该角色的ERole。因为ERole是内存表，数据可能没有  ，请根据堆栈内容确认此使用是否正确。
2016-09-09 15:19:41:129 ERROR BATTLE:mkdb.Worker.procedure.28 - 	at java.lang.Thread.getStackTrace(Unknown Source)
	at fire.pb.effect.RoleImpl.<init>(RoleImpl.java:80)
	at fire.pb.buff.BuffRoleImpl.getERole(BuffRoleImpl.java:252)
	at fire.pb.buff.continual.ConstantlyBuff.impact(ConstantlyBuff.java:102)
	at fire.pb.buff.BuffAgent.addCBuff(BuffAgent.java:294)
	at fire.pb.buff.BuffAgent.addCBuffWithSP(BuffAgent.java:359)
	at fire.pb.role.PAddBuffToCreatRoleProc.process(PAddBuffToCreatRoleProc.java:24)
	at mkdb.Procedure.call(Procedure.java:109)
	at mkdb.Transaction.perform(Transaction.java:279)
	at mkdb.ProcedureFuture.run(ProcedureFuture.java:80)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
	at mkdb.Worker.run(Worker.java:32)

2016-09-09 15:19:41:129 ERROR BATTLE:mkdb.Worker.procedure.28 - 在角色4097下线的情况下，使用了该角色的ERole。因为ERole是内存表，数据可能没有  ，请根据堆栈内容确认此使用是否正确。
2016-09-09 15:19:41:129 ERROR BATTLE:mkdb.Worker.procedure.28 - 	at java.lang.Thread.getStackTrace(Unknown Source)
	at fire.pb.effect.RoleImpl.<init>(RoleImpl.java:80)
	at fire.pb.buff.BuffRoleImpl.getERole(BuffRoleImpl.java:252)
	at fire.pb.buff.continual.ConstantlyBuff.impact(ConstantlyBuff.java:102)
	at fire.pb.buff.BuffAgent.addCBuff(BuffAgent.java:294)
	at fire.pb.buff.BuffAgent.addCBuffWithSP(BuffAgent.java:359)
	at fire.pb.role.PAddBuffToCreatRoleProc.process(PAddBuffToCreatRoleProc.java:29)
	at mkdb.Procedure.call(Procedure.java:109)
	at mkdb.Transaction.perform(Transaction.java:279)
	at mkdb.ProcedureFuture.run(ProcedureFuture.java:80)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
	at mkdb.Worker.run(Worker.java:32)

